# exception handling 异常处理

[toc]

## 异常

#### 异常的概念
- 语法错误：编译器发现
- 逻辑错误：未完成预期功能，静态分析和动态测试发现
- 运行异常(exception)：对运行环境考虑不周，如文件打开失败

#### 异常的处理
- 就地处理
- 异地处理

## C++异常处理

#### `try`、`throw`和`catch`异常处理
```cpp
// 启动异常处理
try{
    <语句序列>
}

// 抛出异常对象
throw <表达式>;

// 捕获异常对象并处理
catch (<类型> <变量>){
    <语句序列>
}
```
- `try`语句若没有抛出异常，则`catch`不执行
- 若`try`语句抛出异常并被`catch`捕获，则`catch`执行完之后执行`catch`之后的语句
- 若`try`语句抛出异常未被`catch`捕获，则由函数调用链的上一层的`catch`捕获
- 若在`try`语句之外抛出异常，不会被`catch`捕获，由系统进行标准异常处理

#### 基于断言的程序调试
- 未定义宏`NDEBUG`时可使用`assert(<表达式>)`判断某个条件是否为真